# Generated by Django 5.1.2 on 2024-10-12 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_payments_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.locationtype'),
        ),
    ]
