# Generated by Django 5.1.2 on 2024-10-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_locations_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
