# Generated by Django 5.1.2 on 2024-10-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_events_event_rename_locations_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approve'), ('DENIED', 'Denied')], default='PENDING', max_length=10),
        ),
    ]
